-- Conferência das migrações (2026-10-09) — SÓ LEITURA, não muda nada.
-- Para cada script da pasta supabase/, procura no banco uma marca que ele deixa (função, tabela,
-- coluna, regra ou dado). "SIM" = já rodado; "NÃO" = falta rodar (na ordem da lista).
-- Scripts que não deixam marca própria aparecem com "—" e a observação.

with
fx  as (select p.proname, p.prosrc from pg_proc p where p.pronamespace = 'public'::regnamespace),
col as (select table_name, column_name from information_schema.columns where table_schema = 'public'),
pathdef as (select pg_get_constraintdef(oid) d from pg_constraint where conname = 'documents_path_valid'),
mfp as (select prosrc s from fx where proname = 'module_for_path'),
lst as (select d.path, i from public.documents d, jsonb_array_elements(coalesce(d.data -> 'list', '[]'::jsonb)) i),
chk (ordem, migracao, aplicada, obs) as (values
 (1,  '2026-09-30-niveis-de-permissao',            exists(select 1 from fx where proname = 'has_perm'), ''),
 (2,  '2026-09-30b-niveis-editaveis',              exists(select 1 from fx where proname = 'roles_before_delete'), 'se NÃO: rodar a 09g, NUNCA a 30b inteira'),
 (3,  '2026-10-01-agenda-por-data',                to_regclass('public.appointments') is not null, ''),
 (4,  '2026-10-01b-servicos',                      exists(select 1 from pathdef where d like '%services%'), ''),
 (5,  '2026-10-01c-servico-no-atendimento',        exists(select 1 from col where table_name = 'appointments' and column_name = 'service'), ''),
 (6,  '2026-10-02-grupos-de-suporte',              exists(select 1 from lst where path = 'config/rooms' and i ->> 'group' = 'true'), ''),
 (7,  '2026-10-02b-varios-atendimentos',           to_regclass('public.appointments_slot_idx') is not null, ''),
 (8,  '2026-10-02c-origem-planner',                exists(select 1 from col where table_name = 'appointments' and column_name = 'source'), ''),
 (9,  '2026-10-02d-status',                        exists(select 1 from fx where proname = 'set_appointment_status'), ''),
 (10, '2026-10-02e-prontuario',                    to_regclass('public.clinical_records') is not null, ''),
 (11, '2026-10-02f-agenda-do-profissional',        exists(select 1 from fx where proname = 'agenda_scope_professional'), ''),
 (12, '2026-10-02g-relatorios',                    exists(select 1 from fx where proname = 'report_appointments_with_records'), ''),
 (13, '2026-10-02h-clinica',                       exists(select 1 from pathdef where d like '%clinic%'), ''),
 (14, '2026-10-02i-finalizado-exige-evolucao',     exists(select 1 from fx where proname = 'appointments_status_guard' and prosrc like '%clinical_records%'), ''),
 (15, '2026-10-02j-nome-usuario-igual-profissional', exists(select 1 from fx where proname = 'sync_professional_user_names'), ''),
 (16, '2026-10-02k-corrige-criar-nivel',           exists(select 1 from fx where proname = 'roles_before_insert'), ''),
 (17, '2026-10-02l-permissoes-cadastros',          exists(select 1 from fx where proname = 'can_write_path'), ''),
 (18, '2026-10-02m-atendimento-com-evolucao',      exists(select 1 from fx where proname = 'appointments_delete_guard'), ''),
 (19, '2026-10-03-copia-de-seguranca',             exists(select 1 from fx where proname = 'appointments_stamp' and prosrc like '%auth.uid() is null%'), ''),
 (20, '2026-10-03b-tratamentos',                   exists(select 1 from pathdef where d like '%treatments/all%'), ''),
 (21, '2026-10-03c-um-tratamento-ativo',           exists(select 1 from fx where proname = 'treatments_one_active'), ''),
 (22, '2026-10-03d-valores-dos-tratamentos',       to_regclass('public.treatment_finance') is not null, ''),
 (23, '2026-10-03e-motivos-de-cancelamento',       exists(select 1 from fx where proname = 'treatments_cancel_rules'), ''),
 (24, '2026-10-04-valores-dos-convenios',          to_regclass('public.convenio_finance') is not null, ''),
 (25, '2026-10-04b-permissoes-menu-acesso',        exists(select 1 from fx where proname = 'profiles_nonadmin_guard'), ''),
 (26, '2026-10-04c-relatorio-financeiro',          exists(select 1 from pg_policies where tablename = 'treatment_finance' and policyname = 'treatment_finance_select' and qual like '%financeiro%'), ''),
 (27, '2026-10-04d-gravar-so-o-tratamento',        exists(select 1 from fx where proname = 'patch_list'), ''),
 (28, '2026-10-04e-resumo-atendimentos-tratamentos', exists(select 1 from fx where proname = 'treatment_appt_summary'), ''),
 (29, '2026-10-05-cadastro-do-paciente',           exists(select 1 from pathdef where d like '%doctors%'), ''),
 (30, '2026-10-05b-conselhos',                     exists(select 1 from pathdef where d like '%councils%'), ''),
 (31, '2026-10-05c-mesclar-e-data-de-entrada',     exists(select 1 from fx where proname = 'merge_patient_records'), ''),
 (32, '2026-10-05d-feriados',                      exists(select 1 from pathdef where d like '%holidays%'), ''),
 (33, '2026-10-05e-rh-funcionarios',               to_regclass('public.staff') is not null, ''),
 (34, '2026-10-05f-profissionais-no-rh',           exists(select 1 from mfp where s not like '%''profissionais''%'), 'substituída pela 05j/07e'),
 (35, '2026-10-05g-funcionarios-dos-usuarios',     null::boolean, 'acerto de dados único; não precisa repetir'),
 (36, '2026-10-05h-cancelado-pode-voltar',         null::boolean, 'desfeita pela 05i; NÃO rodar'),
 (37, '2026-10-05i-cancelado-definitivo',          null::boolean, 'substituída pela 07 (sistema-regras)'),
 (38, '2026-10-05j-cadastro-profissional-segue-colaboradores', exists(select 1 from mfp where s not like '%''profissionais''%'), ''),
 (39, '2026-10-06-plano-terapeutico',              to_regclass('public.therapy_plans') is not null, ''),
 (40, '2026-10-06b-banco-de-objetivos',            exists(select 1 from pathdef where d like '%goal_bank%'), ''),
 (41, '2026-10-06c-objetivos-na-evolucao',         exists(select 1 from col where table_name = 'clinical_records' and column_name = 'plan_goals'), ''),
 (42, '2026-10-06d-finalizado-travado-terapeuta',  exists(select 1 from fx where proname = 'appointments_status_guard' and prosrc like '%terapeuta não altera%'), ''),
 (43, '2026-10-06e-tratamento-sem-vencimento',     not exists(select 1 from lst where path = 'treatments/all' and coalesce(i ->> 'vencPor', '') = ''), 'SIM = nenhum tratamento sem o campo'),
 (44, '2026-10-06f-saude-do-paciente',             to_regclass('public.patient_health') is not null, ''),
 (45, '2026-10-06g-plano-por-habilidade',          exists(select 1 from fx where proname = 'plan_prof_update' and prosrc like '%specIds%'), ''),
 (46, '2026-10-06h-renomear-paciente',             exists(select 1 from fx where proname = 'rename_patient'), ''),
 (47, '2026-10-06i-importacao-cancelado-sem-motivo', exists(select 1 from fx where proname = 'treatments_cancel_rules' and prosrc like '%motivoPendente%'), ''),
 (48, '2026-10-07-sistema-regras',                 exists(select 1 from fx where proname = 'sys_rule'), ''),
 (49, '2026-10-07b-limpeza-campos-antigos',        not exists(select 1 from col where table_name = 'profiles' and column_name = 'is_admin'), ''),
 (50, '2026-10-07c-paciente-por-codigo',           exists(select 1 from col where table_name = 'appointments' and column_name = 'patient_id'), ''),
 (51, '2026-10-07d-colaborador-unico',             not exists(select 1 from lst where path = 'config/professionals' and coalesce(i ->> 'cpf', '') <> ''), ''),
 (52, '2026-10-07e-nomes-internos',                exists(select 1 from col where table_name = 'treatment_finance' and column_name = 'descontos'), ''),
 (53, '2026-10-07f-objetivos-faixa-etaria',        not exists(select 1 from lst where path = 'config/goal_bank' and i ->> 'name' like '[%'), ''),
 (54, '2026-10-08-bloqueio-horario',               exists(select 1 from mfp where s like '%planner_blocks%'), ''),
 (55, '2026-10-08-excluir-tratamentos-de-inativos', null::boolean, 'limpeza opcional já feita; não é migração'),
 (56, '2026-10-08b-disponibilidade',               not exists(select 1 from public.roles r where coalesce((r.permissions -> 'resumo' ->> 'view')::boolean, false) and not (r.permissions ? 'disponibilidade')), 'SIM = nenhum nível pendente'),
 (57, '2026-10-08c-visao-geral',                   not exists(select 1 from public.roles r where coalesce((r.permissions -> 'agenda' ->> 'view')::boolean, false) and not (r.permissions ? 'visao_geral')), 'SIM = nenhum nível pendente'),
 (58, '2026-10-08d-bloqueio-caminho-permitido',    exists(select 1 from pathdef where d like '%planner_blocks%'), ''),
 (59, '2026-10-08e-crm-tarefas',                   to_regclass('public.tasks') is not null, ''),
 (60, '2026-10-08f-crm-finalizada-nao-exclui',     exists(select 1 from fx where proname = 'tasks_delete_guard'), ''),
 (61, '2026-10-09-pacientes-do-grupo',             exists(select 1 from fx where proname = 'group_slot_appointments'), ''),
 (62, '2026-10-09b-paciente-sem-nome-social',      not exists(select 1 from lst where path = 'patients/all' and i ? 'nomeSocial'), ''),
 (63, '2026-10-09c-crm-editar-comentario',         exists(select 1 from col where table_name = 'task_events' and column_name = 'edited_at'), ''),
 (64, '2026-10-09d-permissao-crm',                 not exists(select 1 from public.roles r where not coalesce(r.is_admin, false) and not (coalesce(r.permissions, '{}'::jsonb) ? 'crm_listas')
        and exists(select 1 from jsonb_each(coalesce(r.permissions, '{}'::jsonb)) e where e.key like 'crm\_%' and e.key <> 'crm_listas'
                   and jsonb_typeof(e.value) = 'object' and coalesce((e.value ->> 'view')::boolean, false))), 'SIM = nenhum nível pendente; pode rodar de novo'),
 (65, '2026-10-09e-crm-responsavel-com-acesso',    exists(select 1 from fx where proname = 'crm_user_can'), 'pode rodar de novo sem risco'),
 (66, '2026-10-09f-diagnosticos-e-origens',        exists(select 1 from pathdef where d like '%diagnoses%'), ''),
 (67, '2026-10-09g-acerto-pendentes',              exists(select 1 from fx where proname = 'roles_before_delete') and exists(select 1 from fx where proname = 'treatments_one_active'), 'repõe o que faltava da 30b, 02m, 03c e 08c'),
 (68, '2026-10-10-reinstala-funcoes',              null::boolean, 'conferir com a conferência geral'),
 (69, '2026-10-10b-gravar-so-o-item',              exists(select 1 from fx where proname = 'patch_list2'), ''),
 (70, '2026-10-10c-atendimento-realizado-protegido', exists(select 1 from fx where proname = 'appointments_done_guard'), ''),
 (71, '2026-10-10d-excluir-evolucao',              exists(select 1 from fx where proname = 'clinical_records_plan_goals_undo'), ''),
 (72, '2026-10-10e-excluir-paciente',              exists(select 1 from fx where proname = 'delete_patient_health'), ''),
 (73, '2026-10-10f-mesclar-completo',               exists(select 1 from fx where proname = 'merge_patient_records' and prosrc like '%therapy_plans%'), ''),
 (74, '2026-10-10g-status-protegidos',              exists(select 1 from fx where proname = 'statuses_guard'), ''),
 (75, '2026-10-10h-excluir-plano',                  exists(select 1 from fx where proname = 'therapy_plans_delete_guard'), '')
)
select ordem, migracao,
       case when aplicada is null then '—' when aplicada then 'SIM' else 'NÃO' end as rodada,
       obs
  from chk
 order by (aplicada is distinct from false), ordem;
