-- Conferência geral (2026-10-09) — SÓ LEITURA, não muda nada.
-- Compara o banco com o retrato completo do sistema (supabase/schema.sql).
-- Mostra SÓ o que falta ou está diferente. Nenhuma linha = tudo certo.
with
exp_tab(t) as (values
  ('appointments'),
  ('clinical_records'),
  ('convenio_finance'),
  ('documents'),
  ('patient_health'),
  ('profiles'),
  ('roles'),
  ('staff'),
  ('staff_pay'),
  ('task_events'),
  ('task_reads'),
  ('tasks'),
  ('therapy_plans'),
  ('treatment_finance')),
exp_col(t, c) as (values
  ('appointments', 'blocked'),
  ('appointments', 'created_at'),
  ('appointments', 'created_by'),
  ('appointments', 'date'),
  ('appointments', 'group_id'),
  ('appointments', 'id'),
  ('appointments', 'note'),
  ('appointments', 'patient'),
  ('appointments', 'patient_id'),
  ('appointments', 'professional_id'),
  ('appointments', 'room_id'),
  ('appointments', 'service'),
  ('appointments', 'source'),
  ('appointments', 'status'),
  ('appointments', 'time'),
  ('appointments', 'updated_at'),
  ('appointments', 'updated_by'),
  ('clinical_records', 'appointment_date'),
  ('clinical_records', 'appointment_id'),
  ('clinical_records', 'appointment_time'),
  ('clinical_records', 'author_id'),
  ('clinical_records', 'author_name'),
  ('clinical_records', 'content'),
  ('clinical_records', 'created_at'),
  ('clinical_records', 'id'),
  ('clinical_records', 'patient_id'),
  ('clinical_records', 'patient_name'),
  ('clinical_records', 'plan_goals'),
  ('clinical_records', 'professional_id'),
  ('clinical_records', 'updated_at'),
  ('convenio_finance', 'convenio_id'),
  ('convenio_finance', 'id'),
  ('convenio_finance', 'spec_id'),
  ('convenio_finance', 'updated_at'),
  ('convenio_finance', 'updated_by'),
  ('convenio_finance', 'valor'),
  ('documents', 'data'),
  ('documents', 'path'),
  ('documents', 'updated_at'),
  ('documents', 'updated_by'),
  ('patient_health', 'data'),
  ('patient_health', 'patient_id'),
  ('patient_health', 'updated_at'),
  ('patient_health', 'updated_by'),
  ('profiles', 'active'),
  ('profiles', 'created_at'),
  ('profiles', 'email'),
  ('profiles', 'full_name'),
  ('profiles', 'id'),
  ('profiles', 'professional_id'),
  ('profiles', 'role_id'),
  ('profiles', 'staff_id'),
  ('profiles', 'updated_at'),
  ('roles', 'id'),
  ('roles', 'is_admin'),
  ('roles', 'name'),
  ('roles', 'permissions'),
  ('roles', 'sort'),
  ('roles', 'updated_at'),
  ('staff', 'data'),
  ('staff', 'id'),
  ('staff', 'professional_id'),
  ('staff', 'updated_at'),
  ('staff', 'updated_by'),
  ('staff_pay', 'data'),
  ('staff_pay', 'staff_id'),
  ('staff_pay', 'updated_at'),
  ('staff_pay', 'updated_by'),
  ('task_events', 'author_id'),
  ('task_events', 'author_name'),
  ('task_events', 'body'),
  ('task_events', 'created_at'),
  ('task_events', 'data'),
  ('task_events', 'edited_at'),
  ('task_events', 'id'),
  ('task_events', 'kind'),
  ('task_events', 'mentions'),
  ('task_events', 'task_id'),
  ('task_reads', 'seen_at'),
  ('task_reads', 'task_id'),
  ('task_reads', 'user_id'),
  ('tasks', 'assignees'),
  ('tasks', 'closed_at'),
  ('tasks', 'created_at'),
  ('tasks', 'created_by'),
  ('tasks', 'created_by_name'),
  ('tasks', 'description'),
  ('tasks', 'due_date'),
  ('tasks', 'id'),
  ('tasks', 'lead'),
  ('tasks', 'list_id'),
  ('tasks', 'patient_id'),
  ('tasks', 'position'),
  ('tasks', 'priority'),
  ('tasks', 'status'),
  ('tasks', 'tags'),
  ('tasks', 'title'),
  ('tasks', 'updated_at'),
  ('therapy_plans', 'created_at'),
  ('therapy_plans', 'created_by'),
  ('therapy_plans', 'created_by_name'),
  ('therapy_plans', 'id'),
  ('therapy_plans', 'patient_id'),
  ('therapy_plans', 'patient_name'),
  ('therapy_plans', 'plan_date'),
  ('therapy_plans', 'prev_id'),
  ('therapy_plans', 'review_date'),
  ('therapy_plans', 'sections'),
  ('therapy_plans', 'status'),
  ('therapy_plans', 'summary'),
  ('therapy_plans', 'updated_at'),
  ('therapy_plans', 'updated_by'),
  ('therapy_plans', 'updated_by_name'),
  ('therapy_plans', 'version'),
  ('treatment_finance', 'descontos'),
  ('treatment_finance', 'treatment_id'),
  ('treatment_finance', 'updated_at'),
  ('treatment_finance', 'updated_by'),
  ('treatment_finance', 'valor')),
exp_fn(n, h) as (values
  ('agenda_scope_professional', '69caf20d058300cc92128fced231d275'),
  ('appointments_delete_guard', 'f6c242bc07736eb8a9f90ccd5b7e2f07'),
  ('appointments_refs', '5cd576456216fc36f67bf15be0be0eaf'),
  ('appointments_stamp', '41e1bed5e1792eacc2523a27a6b00f16'),
  ('appointments_status_guard', 'fc302d8e25ecf168265aec3b5d01a810'),
  ('can_set_status', 'ba84846b275409b4fabf7925d68d1de6'),
  ('can_write_path', 'f011d7f914fafffa9a9cf8ab8bc1e4c8'),
  ('clinical_records_plan_goals', 'b419fb66363bd9739edef6aca21fe41d'),
  ('clinical_records_stamp', '28811d0aac28793cdd1444eb67414c1e'),
  ('convenio_finance_stamp', '5f8d1f647d531db818250e18da79ecc9'),
  ('crm_my_name', 'c7c875d60d45e285e7138347b936eb13'),
  ('crm_people', 'af529d4ffe1345f5ee14ed77dc7f113a'),
  ('crm_user_can', '7dbc4d7ae5e2d2e776352a2b3d4bc2c9'),
  ('documents_enforce', 'b5734b6426902289a3213957d74f5beb'),
  ('group_slot_appointments', 'cebabdee97f59640bdb2c4d131470367'),
  ('handle_new_user', '0ed87b180115005b0611b1ce6534d0af'),
  ('has_perm', '68dadef82c344b80be86863d39052e43'),
  ('has_report', '191670d0e1fbf1e17f564a7c5e4c38e4'),
  ('is_active_user', '5bf42edffd371f9a65e8a57ae884538e'),
  ('is_admin', '34bd4ff92ad10a89d86ea89e85e5d27c'),
  ('merge_patient_records', '9d0cd6b2cd439a9b9d4a5c21399f4454'),
  ('module_for_path', 'bd2e4625d04b6b3b7a9aa3d6d8d766cd'),
  ('patch_bookings', 'e4a09d6ddb9b9f24d931534a9460f230'),
  ('patch_list', 'd441ba14dc6eec9e0c999aa978713c83'),
  ('patient_health_stamp', '824b7d4edc0c6653a6a0e00f78cb4140'),
  ('plan_prof_update', 'cb100c4d14315b887c8c706bec25d9a3'),
  ('profiles_guard', '6dcd9bbafaaf8530d611ef37392e4168'),
  ('profiles_nonadmin_guard', '6a03d38669171e47912473ab816893bd'),
  ('profiles_professional_name', '7eff9ba358dd5f2fb09dbc81a4e8c096'),
  ('rename_group', 'ccb636ed2d1526501993b489f4589646'),
  ('rename_patient', 'e53abd6c76394873d4274a1723296944'),
  ('report_appointments_with_records', '07c5570c691fb99719f2fd31a2956f6f'),
  ('roles_before_delete', '75ef417fb7cae859d6721975d622dcb2'),
  ('roles_before_insert', '55f31c35166291f3b6798e6d42193a6f'),
  ('roles_guard', '827148c3e7c282002c7aad193ce0f675'),
  ('set_appointment_status', '4ea2236b179e88a43966bbf2a1f8ffb7'),
  ('staff_stamp', '824b7d4edc0c6653a6a0e00f78cb4140'),
  ('sync_professional_user_names', '07a90e5cd52ead78b9f6296a1c16c6ca'),
  ('sys_rule', '2b78b417ff33c4c10101870e2de35d46'),
  ('task_events_edit_guard', 'e6525e84e65d5c980b93f7a9fef4d55a'),
  ('task_events_stamp', '2f9a91ee8330f9a1f0bdd1b0ddfaba7f'),
  ('tasks_assignees_guard', 'cc597e5295139a0350add2ad922e692f'),
  ('tasks_delete_guard', 'eb6f421315716df8444504af6ec591b0'),
  ('tasks_history', 'ca4df86f3f9e34f2113c909bfe86d175'),
  ('tasks_stamp', '41038cdef586a71c584d50e0a6954fed'),
  ('therapy_plans_stamp', 'c218b651b2f2afabb9568945246db31b'),
  ('treatment_appt_summary', '28f5d2fbc6919ccb0d32cfbdfce4ddb1'),
  ('treatment_finance_stamp', '824b7d4edc0c6653a6a0e00f78cb4140'),
  ('treatments_cancel_rules', '10621bf6ff99c52408e582b76cf5f280'),
  ('treatments_one_active', '9347eff14dde017fecdaab36e73236a8')),
exp_trg(t, n) as (values
  ('appointments', 'appointments_delete_guard'),
  ('appointments', 'appointments_refs'),
  ('appointments', 'appointments_stamp'),
  ('appointments', 'appointments_status_guard'),
  ('clinical_records', 'clinical_records_plan_goals_ins'),
  ('clinical_records', 'clinical_records_plan_goals_upd'),
  ('clinical_records', 'clinical_records_stamp'),
  ('convenio_finance', 'convenio_finance_stamp'),
  ('documents', 'documents_enforce'),
  ('documents', 'documents_sync_professional_names'),
  ('documents', 'treatments_cancel_rules'),
  ('documents', 'treatments_one_active'),
  ('patient_health', 'patient_health_stamp'),
  ('profiles', 'profiles_guard'),
  ('profiles', 'profiles_nonadmin_guard'),
  ('profiles', 'profiles_professional_name'),
  ('roles', 'roles_before_delete'),
  ('roles', 'roles_before_insert'),
  ('roles', 'roles_guard'),
  ('staff', 'staff_stamp'),
  ('staff_pay', 'staff_pay_stamp'),
  ('task_events', 'task_events_edit_guard'),
  ('task_events', 'task_events_stamp'),
  ('tasks', 'tasks_assignees_guard'),
  ('tasks', 'tasks_delete_guard'),
  ('tasks', 'tasks_history'),
  ('tasks', 'tasks_stamp'),
  ('therapy_plans', 'therapy_plans_stamp'),
  ('treatment_finance', 'treatment_finance_stamp')),
exp_pol(t, n) as (values
  ('appointments', 'appointments_delete'),
  ('appointments', 'appointments_insert'),
  ('appointments', 'appointments_select'),
  ('appointments', 'appointments_update'),
  ('clinical_records', 'clinical_records_delete'),
  ('clinical_records', 'clinical_records_insert'),
  ('clinical_records', 'clinical_records_select'),
  ('clinical_records', 'clinical_records_update'),
  ('convenio_finance', 'convenio_finance_delete'),
  ('convenio_finance', 'convenio_finance_insert'),
  ('convenio_finance', 'convenio_finance_select'),
  ('convenio_finance', 'convenio_finance_update'),
  ('documents', 'documents_delete'),
  ('documents', 'documents_insert'),
  ('documents', 'documents_select'),
  ('documents', 'documents_update'),
  ('patient_health', 'patient_health_delete'),
  ('patient_health', 'patient_health_insert'),
  ('patient_health', 'patient_health_select'),
  ('patient_health', 'patient_health_update'),
  ('profiles', 'profiles_select'),
  ('profiles', 'profiles_update'),
  ('roles', 'roles_delete'),
  ('roles', 'roles_insert'),
  ('roles', 'roles_select'),
  ('roles', 'roles_update'),
  ('staff', 'staff_delete'),
  ('staff', 'staff_insert'),
  ('staff', 'staff_select'),
  ('staff', 'staff_update'),
  ('staff_pay', 'staff_pay_delete'),
  ('staff_pay', 'staff_pay_insert'),
  ('staff_pay', 'staff_pay_select'),
  ('staff_pay', 'staff_pay_update'),
  ('task_events', 'task_events_delete'),
  ('task_events', 'task_events_insert'),
  ('task_events', 'task_events_select'),
  ('task_events', 'task_events_update'),
  ('task_reads', 'task_reads_own'),
  ('tasks', 'tasks_delete'),
  ('tasks', 'tasks_insert'),
  ('tasks', 'tasks_select'),
  ('tasks', 'tasks_update'),
  ('therapy_plans', 'therapy_plans_delete'),
  ('therapy_plans', 'therapy_plans_insert'),
  ('therapy_plans', 'therapy_plans_select'),
  ('therapy_plans', 'therapy_plans_update'),
  ('treatment_finance', 'treatment_finance_delete'),
  ('treatment_finance', 'treatment_finance_insert'),
  ('treatment_finance', 'treatment_finance_select'),
  ('treatment_finance', 'treatment_finance_update')),
exp_idx(n) as (values
  ('appointments_date_idx'),
  ('appointments_group_id_idx'),
  ('appointments_patient_id_idx'),
  ('appointments_pkey'),
  ('appointments_slot_idx'),
  ('clinical_records_appt_idx'),
  ('clinical_records_patient_idx'),
  ('clinical_records_pkey'),
  ('convenio_finance_convenio_id_spec_id_key'),
  ('convenio_finance_pkey'),
  ('documents_pkey'),
  ('patient_health_pkey'),
  ('profiles_pkey'),
  ('profiles_professional_unique'),
  ('profiles_staff_id_unique'),
  ('roles_name_unique'),
  ('roles_pkey'),
  ('staff_pay_pkey'),
  ('staff_pkey'),
  ('staff_professional_id_key'),
  ('task_events_mentions_idx'),
  ('task_events_pkey'),
  ('task_events_task_idx'),
  ('task_reads_pkey'),
  ('tasks_assignees_idx'),
  ('tasks_list_idx'),
  ('tasks_pkey'),
  ('therapy_plans_one_vigente'),
  ('therapy_plans_patient'),
  ('therapy_plans_pkey'),
  ('treatment_finance_pkey')),
exp_pub(t) as (values
  ('appointments'),
  ('documents'),
  ('profiles'),
  ('roles'),
  ('task_events'),
  ('tasks')),
exp_path(p) as (values
  ('config/rooms'),
  ('config/specialties'),
  ('config/convenios'),
  ('config/professionals'),
  ('config/services'),
  ('config/statuses'),
  ('config/clinic'),
  ('config/cancel_reasons'),
  ('config/doctors'),
  ('config/schools'),
  ('config/cbo'),
  ('config/councils'),
  ('config/holidays'),
  ('config/staff_types'),
  ('config/patient_fields'),
  ('config/scales'),
  ('config/skill_areas'),
  ('config/goal_bank'),
  ('config/system'),
  ('config/planner_blocks'),
  ('config/task_lists'),
  ('config/diagnoses'),
  ('config/origins'),
  ('patients/all'),
  ('treatments/all'),
  ('schedule/seg-1'),
  ('schedule/sab-4')),
cur_fn as (select p.proname n, md5(p.prosrc) h from pg_proc p where p.pronamespace = 'public'::regnamespace),
pathdef as (select pg_get_constraintdef(oid) d from pg_constraint where conname = 'documents_path_valid'),
falta as (
  select 1 o, 'Tabela faltando' tipo, t item from exp_tab
   where to_regclass('public.' || t) is null
  union all
  select 2, 'Coluna faltando', t || '.' || c from exp_col e
   where to_regclass('public.' || t) is not null
     and not exists (select 1 from information_schema.columns x where x.table_schema = 'public' and x.table_name = e.t and x.column_name = e.c)
  union all
  select 3, 'Função faltando', n from exp_fn e where not exists (select 1 from cur_fn c where c.n = e.n)
  union all
  select 4, 'Função em versão diferente', n from exp_fn e
   where exists (select 1 from cur_fn c where c.n = e.n)
     and not exists (select 1 from cur_fn c where c.n = e.n and c.h = e.h)
  union all
  select 5, 'Gatilho faltando', t || ' → ' || n from exp_trg e
   where not exists (select 1 from pg_trigger g join pg_class c on c.oid = g.tgrelid join pg_namespace s on s.oid = c.relnamespace
                      where s.nspname = 'public' and c.relname = e.t and g.tgname = e.n)
  union all
  select 6, 'Regra de acesso (RLS) faltando', t || ' → ' || n from exp_pol e
   where not exists (select 1 from pg_policies p where p.schemaname = 'public' and p.tablename = e.t and p.policyname = e.n)
  union all
  select 7, 'Tabela sem proteção RLS ligada', t from exp_tab e
   where to_regclass('public.' || t) is not null
     and not (select relrowsecurity from pg_class where oid = to_regclass('public.' || e.t))
  union all
  select 8, 'Índice faltando', n from exp_idx e where to_regclass('public.' || n) is null
  union all
  select 9, 'Tempo real faltando', t from exp_pub e
   where not exists (select 1 from pg_publication_tables p where p.pubname = 'supabase_realtime' and p.tablename = e.t)
  union all
  select 10, 'Caminho de documento não permitido', p from exp_path e
   where not exists (select 1 from pathdef d where e.p ~ substring(d.d from '''(\^.*\$)''')))
select tipo, item from falta order by o, item;
