-- Conferência geral (2026-10-09) — SÓ LEITURA, não muda nada.
-- Compara o banco com o retrato completo do sistema (supabase/schema.sql).
-- Mostra SÓ o que falta ou está diferente. Nenhuma linha = tudo certo.
with
exp_tab(t) as (values
  ('appointments'),
  ('clinical_records'),
  ('convenio_finance'),
  ('documents'),
  ('patient_health'),
  ('profiles'),
  ('roles'),
  ('staff'),
  ('staff_pay'),
  ('task_events'),
  ('task_reads'),
  ('tasks'),
  ('therapy_plans'),
  ('treatment_finance')),
exp_col(t, c) as (values
  ('appointments', 'blocked'),
  ('appointments', 'created_at'),
  ('appointments', 'created_by'),
  ('appointments', 'date'),
  ('appointments', 'group_id'),
  ('appointments', 'id'),
  ('appointments', 'note'),
  ('appointments', 'patient'),
  ('appointments', 'patient_id'),
  ('appointments', 'professional_id'),
  ('appointments', 'room_id'),
  ('appointments', 'service'),
  ('appointments', 'source'),
  ('appointments', 'status'),
  ('appointments', 'time'),
  ('appointments', 'updated_at'),
  ('appointments', 'updated_by'),
  ('clinical_records', 'appointment_date'),
  ('clinical_records', 'appointment_id'),
  ('clinical_records', 'appointment_time'),
  ('clinical_records', 'author_id'),
  ('clinical_records', 'author_name'),
  ('clinical_records', 'content'),
  ('clinical_records', 'created_at'),
  ('clinical_records', 'id'),
  ('clinical_records', 'patient_id'),
  ('clinical_records', 'patient_name'),
  ('clinical_records', 'plan_goals'),
  ('clinical_records', 'professional_id'),
  ('clinical_records', 'updated_at'),
  ('convenio_finance', 'convenio_id'),
  ('convenio_finance', 'id'),
  ('convenio_finance', 'spec_id'),
  ('convenio_finance', 'updated_at'),
  ('convenio_finance', 'updated_by'),
  ('convenio_finance', 'valor'),
  ('documents', 'data'),
  ('documents', 'path'),
  ('documents', 'updated_at'),
  ('documents', 'updated_by'),
  ('patient_health', 'data'),
  ('patient_health', 'patient_id'),
  ('patient_health', 'updated_at'),
  ('patient_health', 'updated_by'),
  ('profiles', 'active'),
  ('profiles', 'created_at'),
  ('profiles', 'email'),
  ('profiles', 'full_name'),
  ('profiles', 'id'),
  ('profiles', 'professional_id'),
  ('profiles', 'role_id'),
  ('profiles', 'staff_id'),
  ('profiles', 'updated_at'),
  ('roles', 'id'),
  ('roles', 'is_admin'),
  ('roles', 'name'),
  ('roles', 'permissions'),
  ('roles', 'sort'),
  ('roles', 'updated_at'),
  ('staff', 'data'),
  ('staff', 'id'),
  ('staff', 'professional_id'),
  ('staff', 'updated_at'),
  ('staff', 'updated_by'),
  ('staff_pay', 'data'),
  ('staff_pay', 'staff_id'),
  ('staff_pay', 'updated_at'),
  ('staff_pay', 'updated_by'),
  ('task_events', 'author_id'),
  ('task_events', 'author_name'),
  ('task_events', 'body'),
  ('task_events', 'created_at'),
  ('task_events', 'data'),
  ('task_events', 'edited_at'),
  ('task_events', 'id'),
  ('task_events', 'kind'),
  ('task_events', 'mentions'),
  ('task_events', 'task_id'),
  ('task_reads', 'seen_at'),
  ('task_reads', 'task_id'),
  ('task_reads', 'user_id'),
  ('tasks', 'assignees'),
  ('tasks', 'closed_at'),
  ('tasks', 'created_at'),
  ('tasks', 'created_by'),
  ('tasks', 'created_by_name'),
  ('tasks', 'description'),
  ('tasks', 'due_date'),
  ('tasks', 'id'),
  ('tasks', 'lead'),
  ('tasks', 'list_id'),
  ('tasks', 'patient_id'),
  ('tasks', 'position'),
  ('tasks', 'priority'),
  ('tasks', 'recurrence'),
  ('tasks', 'status'),
  ('tasks', 'tags'),
  ('tasks', 'title'),
  ('tasks', 'updated_at'),
  ('therapy_plans', 'created_at'),
  ('therapy_plans', 'created_by'),
  ('therapy_plans', 'created_by_name'),
  ('therapy_plans', 'id'),
  ('therapy_plans', 'patient_id'),
  ('therapy_plans', 'patient_name'),
  ('therapy_plans', 'plan_date'),
  ('therapy_plans', 'prev_id'),
  ('therapy_plans', 'review_date'),
  ('therapy_plans', 'sections'),
  ('therapy_plans', 'status'),
  ('therapy_plans', 'summary'),
  ('therapy_plans', 'updated_at'),
  ('therapy_plans', 'updated_by'),
  ('therapy_plans', 'updated_by_name'),
  ('therapy_plans', 'version'),
  ('treatment_finance', 'descontos'),
  ('treatment_finance', 'treatment_id'),
  ('treatment_finance', 'updated_at'),
  ('treatment_finance', 'updated_by'),
  ('treatment_finance', 'valor')),
exp_fn(n, h) as (values
  ('agenda_scope_professional', 'af62a184310a24bb41154aa90f71baef'),
  ('appointments_delete_guard', 'c88f306ad4bd46821049342470921758'),
  ('appointments_done_guard', '744e8b1c49bdf9c2cf8d06f9408713f9'),
  ('appointments_refs', '94a5afdc1187ece0bc9e08277fa713d4'),
  ('appointments_stamp', '18c30a41c26c3d87df21a9b326f36150'),
  ('appointments_status_guard', '9862b3356edf755fb1309678e19e8c48'),
  ('appointments_sync_record', '1e6609f4293e4394422c4cca66f3a1a2'),
  ('can_set_status', '55f87793965991af8b8b383fcb2993ad'),
  ('can_write_path', 'c8f49a69016741da4a1b010d7e90566d'),
  ('clinical_records_delete_guard', '84cd12f6660e04f8f44f1d2183c7d47b'),
  ('clinical_records_plan_goals', 'f7edf02f83d8c15fb765e451126fd531'),
  ('clinical_records_plan_goals_undo', '358b2ca6ea27c685d40c09f2fab17038'),
  ('clinical_records_stamp', '5ec593e9be0ba94ec5805c0f2226ba96'),
  ('convenio_finance_stamp', '4799cf3a18bb3e7287c979636fac477c'),
  ('crm_my_name', '0736c6ff4a326fefdcb40afb933825db'),
  ('crm_people', '1713575f093216b3555b2c8b7111d9c4'),
  ('crm_rec_next', 'ebacec148341e145332bc2fd05700b8a'),
  ('crm_rec_status', '3dcbbda9028db040ae48aaf8a618b7ce'),
  ('crm_status_done', 'ef2701f64c4b31883abb6faabb51b4b6'),
  ('crm_task_usage', '8dd6fa5c485ff62712bd140a1afc5b3f'),
  ('crm_user_can', '02bcf9652cd0e0ac29c4dd6fae96f976'),
  ('delete_patient_health', 'e0dcb580637e2599804525eb2ee40894'),
  ('documents_enforce', '2a4d855c9d06c76f7f7d91b4edbbee09'),
  ('group_slot_appointments', 'f66cd9e53713a9d54ac0080aad946e5d'),
  ('handle_new_user', 'c34d65e62ad2cc56665add2d6b0638d1'),
  ('has_perm', '3c9755542b4fc1ff03b4f6612fc2cca1'),
  ('has_report', '4b518326fe21f6de9c4ad8786a4c51fc'),
  ('is_active_user', '90f6bb0a886bff18323bba87246ea185'),
  ('is_admin', 'fb5e9b633e70f9594f176359718da808'),
  ('merge_patient_records', '529332c0499ec15baf150a522d088db2'),
  ('module_for_path', '56edcb5b7be1ab645cbcc573a23c86f6'),
  ('patch_bookings', 'f1048c245f7da4e753ff3873bde48331'),
  ('patch_list', '544e1fc702d007da62da6425ce3d7f6f'),
  ('patch_list2', '9b462c54eaeb736a12a1e16a5860f964'),
  ('patient_health_stamp', 'ca17694625e84511c0f4e3934edbb770'),
  ('plan_prof_update', 'e4a3d9a49af6abdfde1f9b49f919c159'),
  ('profiles_guard', 'b6db53ddb4e4126bbf0b2033188a99a4'),
  ('profiles_nonadmin_guard', 'e06b659e8dd127fa1344a92cfe99d79f'),
  ('profiles_professional_name', 'b9717cbf5bb69a45cceb5e0179d6e38f'),
  ('rename_group', '6527273319704135e202356fe1dbe22b'),
  ('rename_patient', 'a4288cc6b532671226bbaaf9033d8e62'),
  ('rename_registry_text', '9f069188e2e0d850c5c33076fa87041b'),
  ('report_appointments_with_records', '77a2528de8b2ee67592205d08fabf26d'),
  ('roles_before_delete', '391b19dbc8f2c11b1dfe899ed1a421b7'),
  ('roles_before_insert', 'a2b3e5fc51f2527f4113864f9bcf414d'),
  ('roles_guard', '0554295f3bb4c789314b22480d4f45df'),
  ('set_appointment_status', '8ecc090dd2572780f1b85b0c59198683'),
  ('staff_stamp', 'ca17694625e84511c0f4e3934edbb770'),
  ('statuses_guard', 'ab6870e0c75c5ea6a7326db67f62dfbd'),
  ('sync_professional_user_names', '21208cc9a983631e868a5c63fa3f1628'),
  ('sys_rule', 'edbb8d007a0e58b83314ea88e165b1a7'),
  ('task_events_edit_guard', 'd7f949c361805df9138862136c82b219'),
  ('task_events_stamp', 'e018fe6b83a91ff55357ee7282f221a5'),
  ('task_lists_guard', 'e8bf254146c8351d0f8a6d2e02190287'),
  ('tasks_assignees_guard', '6390b3dab87c3ef16732423248a2c44e'),
  ('tasks_delete_guard', '48324f93d29d1659cfa0a78088337864'),
  ('tasks_history', 'bd8d15d3861a2f7039838e760de7225a'),
  ('tasks_recur', 'f0fc2eaa0a4b5a501a2c8914c40a9a04'),
  ('tasks_stamp', '17e281a8fe419f8fe6c9f6b1ebd921b3'),
  ('therapy_plans_delete_guard', 'ec6fe7063556c5d43a6f921a8502c65f'),
  ('therapy_plans_reopen_prev', 'aa27df2267129f1667e884d531372c89'),
  ('therapy_plans_stamp', '753a171dee055d4550e16e39ef7abab2'),
  ('treatment_appt_summary', '1963700905228880585338bd1df1721d'),
  ('treatment_finance_stamp', 'ca17694625e84511c0f4e3934edbb770'),
  ('treatments_cancel_rules', '033b87291563e40d9791203e070d980a'),
  ('treatments_one_active', '33366ead76f798d9f13d206f54f40959')),
exp_trg(t, n) as (values
  ('appointments', 'appointments_delete_guard'),
  ('appointments', 'appointments_done_guard'),
  ('appointments', 'appointments_refs'),
  ('appointments', 'appointments_stamp'),
  ('appointments', 'appointments_status_guard'),
  ('appointments', 'appointments_sync_record'),
  ('clinical_records', 'clinical_records_delete_guard'),
  ('clinical_records', 'clinical_records_plan_goals_del'),
  ('clinical_records', 'clinical_records_plan_goals_ins'),
  ('clinical_records', 'clinical_records_plan_goals_unmark'),
  ('clinical_records', 'clinical_records_plan_goals_upd'),
  ('clinical_records', 'clinical_records_stamp'),
  ('convenio_finance', 'convenio_finance_stamp'),
  ('documents', 'documents_enforce'),
  ('documents', 'documents_sync_professional_names'),
  ('documents', 'statuses_guard'),
  ('documents', 'task_lists_guard'),
  ('documents', 'treatments_cancel_rules'),
  ('documents', 'treatments_one_active'),
  ('patient_health', 'patient_health_stamp'),
  ('profiles', 'profiles_guard'),
  ('profiles', 'profiles_nonadmin_guard'),
  ('profiles', 'profiles_professional_name'),
  ('roles', 'roles_before_delete'),
  ('roles', 'roles_before_insert'),
  ('roles', 'roles_guard'),
  ('staff', 'staff_stamp'),
  ('staff_pay', 'staff_pay_stamp'),
  ('task_events', 'task_events_edit_guard'),
  ('task_events', 'task_events_stamp'),
  ('tasks', 'tasks_assignees_guard'),
  ('tasks', 'tasks_delete_guard'),
  ('tasks', 'tasks_history'),
  ('tasks', 'tasks_recur'),
  ('tasks', 'tasks_stamp'),
  ('therapy_plans', 'therapy_plans_delete_guard'),
  ('therapy_plans', 'therapy_plans_reopen_prev'),
  ('therapy_plans', 'therapy_plans_stamp'),
  ('treatment_finance', 'treatment_finance_stamp')),
exp_pol(t, n) as (values
  ('appointments', 'appointments_delete'),
  ('appointments', 'appointments_insert'),
  ('appointments', 'appointments_select'),
  ('appointments', 'appointments_update'),
  ('clinical_records', 'clinical_records_delete'),
  ('clinical_records', 'clinical_records_insert'),
  ('clinical_records', 'clinical_records_select'),
  ('clinical_records', 'clinical_records_update'),
  ('convenio_finance', 'convenio_finance_delete'),
  ('convenio_finance', 'convenio_finance_insert'),
  ('convenio_finance', 'convenio_finance_select'),
  ('convenio_finance', 'convenio_finance_update'),
  ('documents', 'documents_delete'),
  ('documents', 'documents_insert'),
  ('documents', 'documents_select'),
  ('documents', 'documents_update'),
  ('patient_health', 'patient_health_delete'),
  ('patient_health', 'patient_health_insert'),
  ('patient_health', 'patient_health_select'),
  ('patient_health', 'patient_health_update'),
  ('profiles', 'profiles_select'),
  ('profiles', 'profiles_update'),
  ('roles', 'roles_delete'),
  ('roles', 'roles_insert'),
  ('roles', 'roles_select'),
  ('roles', 'roles_update'),
  ('staff', 'staff_delete'),
  ('staff', 'staff_insert'),
  ('staff', 'staff_select'),
  ('staff', 'staff_update'),
  ('staff_pay', 'staff_pay_delete'),
  ('staff_pay', 'staff_pay_insert'),
  ('staff_pay', 'staff_pay_select'),
  ('staff_pay', 'staff_pay_update'),
  ('task_events', 'task_events_delete'),
  ('task_events', 'task_events_insert'),
  ('task_events', 'task_events_select'),
  ('task_events', 'task_events_update'),
  ('task_reads', 'task_reads_own'),
  ('tasks', 'tasks_delete'),
  ('tasks', 'tasks_insert'),
  ('tasks', 'tasks_select'),
  ('tasks', 'tasks_update'),
  ('therapy_plans', 'therapy_plans_delete'),
  ('therapy_plans', 'therapy_plans_insert'),
  ('therapy_plans', 'therapy_plans_select'),
  ('therapy_plans', 'therapy_plans_update'),
  ('treatment_finance', 'treatment_finance_delete'),
  ('treatment_finance', 'treatment_finance_insert'),
  ('treatment_finance', 'treatment_finance_select'),
  ('treatment_finance', 'treatment_finance_update')),
exp_idx(n) as (values
  ('appointments_date_idx'),
  ('appointments_group_id_idx'),
  ('appointments_patient_id_idx'),
  ('appointments_pkey'),
  ('appointments_slot_idx'),
  ('clinical_records_appt_idx'),
  ('clinical_records_patient_idx'),
  ('clinical_records_pkey'),
  ('convenio_finance_convenio_id_spec_id_key'),
  ('convenio_finance_pkey'),
  ('documents_pkey'),
  ('patient_health_pkey'),
  ('profiles_pkey'),
  ('profiles_professional_unique'),
  ('profiles_staff_id_unique'),
  ('roles_name_unique'),
  ('roles_pkey'),
  ('staff_pay_pkey'),
  ('staff_pkey'),
  ('staff_professional_id_key'),
  ('task_events_mentions_idx'),
  ('task_events_pkey'),
  ('task_events_task_idx'),
  ('task_reads_pkey'),
  ('tasks_assignees_idx'),
  ('tasks_list_idx'),
  ('tasks_pkey'),
  ('therapy_plans_one_vigente'),
  ('therapy_plans_patient'),
  ('therapy_plans_pkey'),
  ('treatment_finance_pkey')),
exp_pub(t) as (values
  ('appointments'),
  ('documents'),
  ('profiles'),
  ('roles'),
  ('task_events'),
  ('tasks')),
exp_path(p) as (values
  ('config/rooms'),
  ('config/specialties'),
  ('config/convenios'),
  ('config/professionals'),
  ('config/services'),
  ('config/statuses'),
  ('config/clinic'),
  ('config/cancel_reasons'),
  ('config/doctors'),
  ('config/schools'),
  ('config/cbo'),
  ('config/councils'),
  ('config/holidays'),
  ('config/staff_types'),
  ('config/patient_fields'),
  ('config/scales'),
  ('config/skill_areas'),
  ('config/goal_bank'),
  ('config/system'),
  ('config/planner_blocks'),
  ('config/task_lists'),
  ('config/diagnoses'),
  ('config/origins'),
  ('patients/all'),
  ('treatments/all'),
  ('schedule/seg-1'),
  ('schedule/sab-4')),
cur_fn as (select p.proname n, md5(replace(replace(replace(replace(p.prosrc, ' ', ''), chr(9), ''), chr(10), ''), chr(13), '')) h from pg_proc p where p.pronamespace = 'public'::regnamespace),
pathdef as (select pg_get_constraintdef(oid) d from pg_constraint where conname = 'documents_path_valid'),
falta as (
  select 1 o, 'Tabela faltando' tipo, t item from exp_tab
   where to_regclass('public.' || t) is null
  union all
  select 2, 'Coluna faltando', t || '.' || c from exp_col e
   where to_regclass('public.' || t) is not null
     and not exists (select 1 from information_schema.columns x where x.table_schema = 'public' and x.table_name = e.t and x.column_name = e.c)
  union all
  select 3, 'Função faltando', n from exp_fn e where not exists (select 1 from cur_fn c where c.n = e.n)
  union all
  select 4, 'Função em versão diferente', n from exp_fn e
   where exists (select 1 from cur_fn c where c.n = e.n)
     and not exists (select 1 from cur_fn c where c.n = e.n and c.h = e.h)
  union all
  select 5, 'Gatilho faltando', t || ' → ' || n from exp_trg e
   where not exists (select 1 from pg_trigger g join pg_class c on c.oid = g.tgrelid join pg_namespace s on s.oid = c.relnamespace
                      where s.nspname = 'public' and c.relname = e.t and g.tgname = e.n)
  union all
  select 6, 'Regra de acesso (RLS) faltando', t || ' → ' || n from exp_pol e
   where not exists (select 1 from pg_policies p where p.schemaname = 'public' and p.tablename = e.t and p.policyname = e.n)
  union all
  select 7, 'Tabela sem proteção RLS ligada', t from exp_tab e
   where to_regclass('public.' || t) is not null
     and not (select relrowsecurity from pg_class where oid = to_regclass('public.' || e.t))
  union all
  select 8, 'Índice faltando', n from exp_idx e where to_regclass('public.' || n) is null
  union all
  select 9, 'Tempo real faltando', t from exp_pub e
   where not exists (select 1 from pg_publication_tables p where p.pubname = 'supabase_realtime' and p.tablename = e.t)
  union all
  select 10, 'Caminho de documento não permitido', p from exp_path e
   where not exists (select 1 from pathdef d where e.p ~ substring(d.d from '''(\^.*\$)''')))
select tipo, item from falta order by o, item;
